# Generated by Django 6.0.1 on 2026-06-04 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karigar',
            fields=[
                ('karigar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the karigar.', max_length=150)),
            ],
            options={
                'verbose_name': 'Karigar',
                'verbose_name_plural': 'Karigars',
                'db_table': 'karigar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KarigarPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', help_text='Pending = not yet paid; Partial = partially paid; Paid = fully settled.', max_length=10)),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional notes (advance, final settlement, partial, etc.).')),
                ('karigar', models.ForeignKey(help_text='Karigar who received this payment.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='production.karigar')),
            ],
            options={
                'verbose_name': 'Karigar Payment',
                'verbose_name_plural': 'Karigar Payments',
                'db_table': 'karigar_payment',
                'ordering': ['-payment_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='chk_karigar_payment_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('length_assigned', models.DecimalField(decimal_places=2, help_text='Cloth length handed over to this karigar in metres.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('planned_kurtas', models.PositiveIntegerField(help_text='Number of kurtas expected from this assignment.')),
                ('actual_kurtas_made', models.PositiveIntegerField(default=0, help_text='Kurtas actually delivered by the karigar so far.')),
                ('price_per_piece', models.DecimalField(decimal_places=2, help_text='Labour cost per kurta paid to karigar. NOT the selling price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_assigned', models.DateField(default=django.utils.timezone.now, help_text='Date cloth was physically handed over to karigar.')),
                ('remaining_length_after_making', models.DecimalField(decimal_places=2, default=0, help_text='Cloth returned unused after production (waste tracking).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('karigar', models.ForeignKey(help_text='Karigar assigned to stitch kurtas for this assignment.', on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.karigar')),
                ('thaan', models.ForeignKey(help_text='Thaan from which cloth was taken for this assignment.', on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='inventory.thaan')),
            ],
            options={
                'verbose_name': 'Production Assignment',
                'verbose_name_plural': 'Production Assignments',
                'db_table': 'production',
                'ordering': ['-date_assigned'],
                'indexes': [models.Index(fields=['thaan'], name='idx_prod_thaan'), models.Index(fields=['karigar'], name='idx_prod_karigar'), models.Index(fields=['status'], name='idx_prod_status'), models.Index(fields=['date_assigned'], name='idx_prod_date_assigned')],
                'constraints': [models.CheckConstraint(condition=models.Q(('length_assigned__gt', 0)), name='chk_prod_length_assigned_positive'), models.CheckConstraint(condition=models.Q(('planned_kurtas__gt', 0)), name='chk_prod_planned_kurtas_positive'), models.CheckConstraint(condition=models.Q(('actual_kurtas_made__gte', 0)), name='chk_prod_actual_kurtas_non_negative'), models.CheckConstraint(condition=models.Q(('price_per_piece__gte', 0)), name='chk_prod_price_per_piece_non_negative'), models.CheckConstraint(condition=models.Q(('remaining_length_after_making__gte', 0)), name='chk_prod_remaining_length_non_negative')],
            },
        ),
    ]
