# Generated by Django 6.0.1 on 2026-06-15 17:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karigar',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='karigarpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='karigarpayment',
            name='karigar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='production.karigar'),
        ),
        migrations.AlterField(
            model_name='karigarpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='karigarpayment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='production',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='production',
            name='karigar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.karigar'),
        ),
        migrations.AlterField(
            model_name='production',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, help_text='Labour cost per kurta (NOT the selling price).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='remaining_length_after_making',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unused cloth returned after production.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='production',
            name='thaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='inventory.thaan'),
        ),
    ]
