# Generated by Django 6.0.1 on 2026-06-16 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_karigar_name_alter_karigarpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='remaining_length_after_making',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, help_text='Cloth length handed over to this karigar in metres.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]), help_text='Unused cloth returned after production.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
