# Generated by Django 6.0.1 on 2026-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_production_remaining_length_after_making'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karigarpayment',
            name='payment_status',
        ),
    ]
