# Generated by Django 6.0.1 on 2026-06-04 07:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('billing_staff', 'Billing Staff'), ('viewer', 'Viewer')], default='viewer', help_text='Business role controlling what this user can access.', max_length=20)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number.', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9-15 digits, optional +country code).', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text='Required. Must be unique across all users.', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user_custom',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Created Record'), ('update', 'Updated Record'), ('delete', 'Deleted Record'), ('bill_generated', 'Bill Generated')], help_text='Type of action performed.', max_length=20)),
                ('model_name', models.CharField(blank=True, default='', help_text='Which model was affected (e.g. Bill, Production, KurtaStock).', max_length=100)),
                ('object_id', models.CharField(blank=True, default='', help_text='Primary key of the affected object.', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of what happened.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Exact time the action occurred.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True)),
                ('user', models.ForeignKey(help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='idx_log_user'), models.Index(fields=['action'], name='idx_log_action'), models.Index(fields=['timestamp'], name='idx_log_timestamp'), models.Index(fields=['model_name'], name='idx_log_model_name')],
            },
        ),
    ]
