# Generated by Django 6.0.1 on 2026-06-04 07:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text='Unique brand / supplier name.', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Thaan',
            fields=[
                ('thaan_no', models.PositiveIntegerField(help_text='Unique manually-assigned Thaan number (e.g. 12201).', primary_key=True, serialize=False)),
                ('total_length', models.DecimalField(decimal_places=2, help_text='Total cloth length in metres as received.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('remaining_length', models.DecimalField(decimal_places=2, help_text='Cloth still available for assignment. Auto-updated via signals.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', help_text='Active = cloth still available; Completed = fully assigned.', max_length=20)),
                ('date_received', models.DateField(default=django.utils.timezone.now, help_text='Date this thaan was received in the warehouse.')),
                ('brand', models.ForeignKey(help_text='Brand that supplied this thaan.', on_delete=django.db.models.deletion.PROTECT, related_name='thaans', to='inventory.brand')),
            ],
            options={
                'verbose_name': 'Thaan',
                'verbose_name_plural': 'Thaans',
                'db_table': 'thaan',
                'ordering': ['-date_received', 'thaan_no'],
            },
        ),
        migrations.CreateModel(
            name='ThaanPurchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Supplier invoice number — must be unique.', max_length=100, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Amount paid or to be paid for this thaan.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('brand', models.ForeignKey(help_text='Denormalised brand for fast filtering (must match thaan.brand).', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.brand')),
                ('thaan', models.ForeignKey(help_text='Which thaan this purchase record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.thaan')),
            ],
            options={
                'verbose_name': 'Thaan Purchase',
                'verbose_name_plural': 'Thaan Purchases',
                'db_table': 'thaan_purchase',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='thaan',
            index=models.Index(fields=['brand'], name='idx_thaan_brand'),
        ),
        migrations.AddIndex(
            model_name='thaan',
            index=models.Index(fields=['status'], name='idx_thaan_status'),
        ),
        migrations.AddIndex(
            model_name='thaan',
            index=models.Index(fields=['date_received'], name='idx_thaan_date_received'),
        ),
        migrations.AddConstraint(
            model_name='thaan',
            constraint=models.CheckConstraint(condition=models.Q(('total_length__gt', 0)), name='chk_thaan_total_length_positive'),
        ),
        migrations.AddConstraint(
            model_name='thaan',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_length__gte', 0)), name='chk_thaan_remaining_length_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='thaan',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_length__lte', models.F('total_length'))), name='chk_thaan_remaining_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='thaanpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('price_paid__gte', 0)), name='chk_purchase_price_paid_non_negative'),
        ),
    ]
