# Generated by Django 6.0.1 on 2026-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='thaanpurchase',
            name='chk_purchase_price_paid_non_negative',
        ),
        migrations.DeleteModel(
            name='ThaanPurchase',
        ),
    ]
