# Generated by Django 6.0.1 on 2026-06-04 07:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Name of the customer for this bill.', max_length=200)),
                ('bill_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the sale.')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bill',
                'ordering': ['-bill_date', '-bill_no'],
                'indexes': [models.Index(fields=['bill_date'], name='idx_bill_date'), models.Index(fields=['customer_name'], name='idx_bill_customer_name')],
            },
        ),
        migrations.CreateModel(
            name='KurtaStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.PositiveSmallIntegerField(choices=[(32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46'), (48, '48')], help_text='Kurta size. Valid values: 32, 34, 36, 38, 40, 42, 44, 46, 48.')),
                ('produced_quantity', models.PositiveIntegerField(default=0, help_text='Total kurtas produced for this thaan + size combination.')),
                ('sold_quantity', models.PositiveIntegerField(default=0, help_text='Total kurtas sold so far. Auto-updated by signals on billing.')),
                ('thaan', models.ForeignKey(help_text='Thaan from which these kurtas were produced.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.thaan')),
            ],
            options={
                'verbose_name': 'Kurta Stock',
                'verbose_name_plural': 'Kurta Stock',
                'db_table': 'kurta_stock',
                'ordering': ['thaan', 'size'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Number of kurtas sold in this line item.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price per kurta — entered manually at billing time.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bill', models.ForeignKey(help_text='Parent bill this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.bill')),
                ('stock', models.ForeignKey(help_text='Stock entry being sold (provides thaan + size).', on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='sales.kurtastock')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'db_table': 'bill_item',
                'ordering': ['bill', 'item_id'],
            },
        ),
        migrations.AddIndex(
            model_name='kurtastock',
            index=models.Index(fields=['thaan', 'size'], name='idx_stock_thaan_size'),
        ),
        migrations.AddIndex(
            model_name='kurtastock',
            index=models.Index(fields=['thaan'], name='idx_stock_thaan'),
        ),
        migrations.AddConstraint(
            model_name='kurtastock',
            constraint=models.CheckConstraint(condition=models.Q(('produced_quantity__gte', 0)), name='chk_stock_produced_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='kurtastock',
            constraint=models.CheckConstraint(condition=models.Q(('sold_quantity__gte', 0)), name='chk_stock_sold_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='kurtastock',
            constraint=models.CheckConstraint(condition=models.Q(('sold_quantity__lte', models.F('produced_quantity'))), name='chk_stock_sold_lte_produced'),
        ),
        migrations.AlterUniqueTogether(
            name='kurtastock',
            unique_together={('thaan', 'size')},
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='chk_bill_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='chk_bill_item_price_positive'),
        ),
    ]
